service: sheets-shop

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  environment:
    SHEETS_API_KEY: ${file(env.json):SHEETS_API_KEY}
    SPREADSHEET_ID: ${file(env.json):SPREADSHEET_ID}

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  hello:
    handler: src/handler.hello
    events:
      - http: 
          path: /
          method: get
